version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wafflebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9232:5432"
    networks:
      - default

  nats:
    image: nats:2.9.18-alpine
    command:
      - -a=0.0.0.0
      - -p=4222
      - --jetstream
    ports:
      - "9243:4222"

  jaeger:
    image: jaegertracing/all-in-one:1.45
    ports:
      - "9286:16686"
      - "9217:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  default:
