version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wafflebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9232:5432"
    networks:
      - default

  jaeger:
    image: jaegertracing/all-in-one:1.45
    ports:
      - "9286:16686"
      - "9217:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  default:
