version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wafflebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9232:5432"
    networks:
      - default

networks:
  default:
