"""Remove email field from user

Revision ID: 0050251979c5
Revises: a2545f11cbf8
Create Date: 2021-04-02 20:02:05.766869+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0050251979c5"
down_revision = "a2545f11cbf8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
