"""Add channel id to panel

Revision ID: 2758fed485f5
Revises: 85a2851269ca
Create Date: 2021-04-04 22:59:43.008425+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2758fed485f5"
down_revision = "85a2851269ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "panels", sa.Column("channel_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("panels", "channel_id")
    # ### end Alembic commands ###
