"""Remove unused column

Revision ID: 37b2cff7ac8d
Revises: 485d2a94f8f4
Create Date: 2021-04-04 22:41:09.594403+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37b2cff7ac8d"
down_revision = "485d2a94f8f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "is_reaction")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "is_reaction", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
