"""Add created at for ticket

Revision ID: 61fead81e7a2
Revises: f90d606fedf5
Create Date: 2021-04-04 03:01:46.287347+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61fead81e7a2"
down_revision = "f90d606fedf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "created_at")
    # ### end Alembic commands ###
