"""Add admin access

Revision ID: 6fc84fec082d
Revises: 9ccd11db28bd
Create Date: 2021-08-12 05:39:33.435754+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fc84fec082d"
down_revision = "9ccd11db28bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.schema.DefaultClause("0"),
        ),
    )
    op.drop_column("users", "has_panel")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "has_panel",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.schema.DefaultClause("0"),
        ),
    )
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
