"""Add created at for message

Revision ID: 85a2851269ca
Revises: 37b2cff7ac8d
Create Date: 2021-04-04 22:44:37.250337+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85a2851269ca"
down_revision = "37b2cff7ac8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "created_at")
    # ### end Alembic commands ###
