"""Cascade delete foreign keys

Revision ID: 9046587a9e7e
Revises: 2758fed485f5
Create Date: 2021-04-05 20:21:07.374295+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9046587a9e7e"
down_revision = "2758fed485f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "messages_ticket_id_fkey", "messages", type_="foreignkey"
    )
    op.drop_constraint(
        "messages_sender_id_fkey", "messages", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "messages", "tickets", ["ticket_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "messages", "users", ["sender_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "reactions_panel_id_fkey", "reactions", type_="foreignkey"
    )
    op.drop_constraint(
        "reactions_category_id_fkey", "reactions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "reactions", "panels", ["panel_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "reactions",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "tickets_creator_id_fkey", "tickets", type_="foreignkey"
    )
    op.drop_constraint(
        "tickets_category_id_fkey", "tickets", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "tickets", "users", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "tickets",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.create_foreign_key(
        "tickets_category_id_fkey",
        "tickets",
        "categories",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "tickets_creator_id_fkey", "tickets", "users", ["creator_id"], ["id"]
    )
    op.drop_constraint(None, "reactions", type_="foreignkey")
    op.drop_constraint(None, "reactions", type_="foreignkey")
    op.create_foreign_key(
        "reactions_category_id_fkey",
        "reactions",
        "categories",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "reactions_panel_id_fkey", "reactions", "panels", ["panel_id"], ["id"]
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_sender_id_fkey", "messages", "users", ["sender_id"], ["id"]
    )
    op.create_foreign_key(
        "messages_ticket_id_fkey", "messages", "tickets", ["ticket_id"], ["id"]
    )
    # ### end Alembic commands ###
