"""Add announcements

Revision ID: a1e821917967
Revises: 6fc84fec082d
Create Date: 2021-08-12 15:47:52.310875+00:00

"""
from alembic import op
from common.database.tables.types import TimeStamp
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1e821917967"
down_revision = "6fc84fec082d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("send_at", TimeStamp(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embed", sa.Boolean(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.CheckConstraint("embed = false OR (embed = true AND title IS NOT NULL)"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_announcements_id"), "announcements", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcements_id"), table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
