"""Add friendly names to announcements

Revision ID: f5d027f1794b
Revises: a1e821917967
Create Date: 2021-08-14 00:23:11.363458+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5d027f1794b"
down_revision = "a1e821917967"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column("name", sa.String(length=128), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "name")
    # ### end Alembic commands ###
