from aioredis import Redis
from typing import List

from .keys import Key, Type


class KV(object):
    def __init__(self, redis: Redis):
        self.__redis = redis

        # Add a getter and setter for each key
        for key in Key:
            if key not in Key.exclude_autogenerated():
                fn = self.__get_or_set(key)
                setattr(self, key.value, fn)

    @classmethod
    async def connect(cls, url: str):
        """
        Connect to a Redis instance for the KV store
        :param url: the url for the Redis instance
        """
        redis = Redis.from_url(
            url, encoding="utf-8", decode_responses=True, max_connections=64
        )
        await redis.ping()
        return cls(redis)

    async def disconnect(self):
        """
        Disconnect from all active Redis connections
        """
        await self.__redis.connection_pool.disconnect(inuse_connections=True)

    def __get_or_set(self, key: Key):
        """
        A helper function for getting or setting a value into Redis at a give key
        :param key: the key to operate at
        """

        async def inner(value: int = None) -> int:
            # Fetch the value
            if value is None:
                result = await self.__redis.get(key.value)
                if result is None:
                    return -1
                return int(result)

            # Set the value
            await self.__redis.set(key.value, value)
            return value

        # Set the function name and docstring
        inner.__name__ = key.value
        inner.__doc__ = (
            f"Get or set the {key.value.split('_')}\n"
            f":param value: the value to set, None when getting value"
        )

        return inner

    async def get_multiple(self, *keys: Key) -> List[int]:
        """
        Get the values of multiple keys at once
        :param keys: the keys to get
        """
        # Ensure keys are unique
        unique = set(keys)

        result = []
        for key in unique:
            if key in Key.exclude_autogenerated():
                result += await getattr(self, key.value)()
            else:
                value = await getattr(self, key.value)()
                result.append(value)

        return result
