from enum import Enum
from typing import List


class Type(Enum):
    Role = "role"
    TextChannel = "text_channel"


class Key(Enum):
    ManagementRole = "management_role"
    PanelAccessRole = "panel_access_role"
    RegisteredRole = "registered_role"
    AnnouncementsChannel = "announcements_channel"

    def type(self) -> Type:
        """
        The type of value stored at the given key
        """
        return {
            Key.ManagementRole.value: Type.Role,
            Key.PanelAccessRole.value: Type.Role,
            Key.RegisteredRole.value: Type.Role,
            Key.AnnouncementsChannel.value: Type.Role,
        }[self.value]

    @staticmethod
    def exclude_autogenerated() -> List["Key"]:
        """
        The keys to not autogenerate getters/setters for
        """
        return []
